[metadata]
name = yt-dlp-instagram-hdr
version = 0.3.2
description = yt-dlp plugin for downloading HDR Instagram videos, Reels, and Stories
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/viniciusron7/yt-dlp-instagram-hdr
license = MIT
license_files = LICENSE

[options]
packages = find_namespace:
python_requires = >=3.10
install_requires =
    yt-dlp>=2026.8.19

[options.packages.find]
include =
    yt_dlp_plugins.*
